# packages in environment at /Users/thomasryde/opt/anaconda3/envs/myenv:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appnope                   0.1.2           py39hecd8cb5_1001  
arrow                     1.2.1                    pypi_0    pypi
awscli                    1.22.27                  pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
binaryornot               0.4.4                    pypi_0    pypi
botocore                  1.23.27                  pypi_0    pypi
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8        py39h6e9494a_1    conda-forge
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.9                    pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
cookiecutter              1.7.3                    pypi_0    pypi
coverage                  6.2                      pypi_0    pypi
debugpy                   1.5.1            py39h9fcab8e_0    conda-forge
decorator                 5.1.0              pyhd3eb1b0_0  
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
flake8                    4.0.1                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
ipykernel                 6.6.0            py39h71a6800_0    conda-forge
ipython                   7.29.0           py39h01d92e1_0  
jedi                      0.18.0           py39hecd8cb5_1  
jinja2                    3.0.3                    pypi_0    pypi
jinja2-time               0.2.0                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py39h6e9494a_1    conda-forge
libcxx                    12.0.0               h2f01273_0  
libffi                    3.3                  hb1e8313_2  
libsodium                 1.0.18               hbcb3906_1    conda-forge
markupsafe                2.0.1                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mccabe                    0.6.1                    pypi_0    pypi
ncurses                   6.3                  hca72f7f_2  
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
numpy                     1.22.0                   pypi_0    pypi
openssl                   1.1.1l               h0d85af4_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
parso                     0.8.2              pyhd3eb1b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pip                       21.3.1                   pypi_0    pypi
pipreqs                   0.4.11                   pypi_0    pypi
poyo                      0.5.0                    pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyasn1                    0.4.8                    pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pyflakes                  2.4.0                    pypi_0    pypi
pygments                  2.10.0             pyhd3eb1b0_0  
pyparsing                 3.0.6                    pypi_0    pypi
python                    3.9.7                h88f2d9e_1  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-dotenv             0.19.2                   pypi_0    pypi
python-slugify            5.0.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3                   pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.3.0           py39h7fec2f1_1    conda-forge
readline                  8.1                  h9ed2024_0  
requests                  2.26.0                   pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
s3transfer                0.5.0                    pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    4.3.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.37.0               h707629a_0  
text-unidecode            1.3                      pypi_0    pypi
tk                        8.6.11               h7bc2e8c_0  
torch                     1.10.1                   pypi_0    pypi
tornado                   6.1              py39h89e85a6_2    conda-forge
traitlets                 5.1.1              pyhd3eb1b0_0  
typing-extensions         4.0.1                    pypi_0    pypi
tzdata                    2021e                hda174b7_0  
urllib3                   1.26.7                   pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
wheel                     0.37.1                   pypi_0    pypi
xz                        5.2.5                h1de35cc_0  
yarg                      0.1.9                    pypi_0    pypi
zeromq                    4.3.4                he49afe7_1    conda-forge
zlib                      1.2.11               h4dc903c_4  
